[package]
name = "fleetfs"
description = "FleetFS"
license = "Apache-2.0"
version = "0.0.0"
authors = ["Christopher Berner <christopherberner@gmail.com>"]

[dependencies]
bytes = "0.4"
futures = "0.1"
hyper = "0.12"
clap = "2.32"
serde_json = "1"
