[package]
name = "fleetfs"
description = "FleetFS"
license = "Apache-2.0"
version = "0.0.0"
authors = ["Christopher Berner <christopherberner@gmail.com>"]
edition = "2018"

[dependencies]
bytes = "0.4"
futures = "0.1"
hyper = "0.12"
tokio = "0.1"
tokio-io = "0.1"
clap = "2.32"
serde_json = "1.0"
log = "0.4"
env_logger = "0.6"
fuse_mt = "0.4"
time = "0.1"
libc = "0.2"
reqwest = "0.9"
byteorder = "1.3"

[profile.release]
debug = true
