[package]
name = "fleetfs"
description = "FleetFS"
license = "Apache-2.0"
version = "0.0.0"
authors = ["Christopher Berner <christopherberner@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.1"
tokio = "0.1"
clap = "2.32"
log = "0.4"
env_logger = "0.6"
fuse_mt = {git = "https://github.com/cberner/fuse-mt.git", branch = "borrow_read"}
time = "0.1"
libc = "0.2"
byteorder = "1.3"
flatbuffers = "0.6.0"
filetime = "0.2"
thread_local = "0.3"

[profile.release]
debug = true
