FROM ubuntu:24.04

ARG DEBIAN_FRONTEND=noninteractive

# ubuntu:24.04 only enables main+restricted by default; universe is needed for fuse, bsdmainutils, dbench, etc.
RUN sed -i 's/Components: main restricted/Components: main restricted universe multiverse/g' /etc/apt/sources.list.d/ubuntu.sources

RUN apt update && apt install -y git build-essential autoconf curl cmake fuse bc libtool \
  uuid-dev xfslibs-dev libattr1-dev libacl1-dev libaio-dev attr acl quota bsdmainutils dbench psmisc

RUN adduser --disabled-password --gecos '' fsgqa

RUN echo 'user_allow_other' >> /etc/fuse.conf

RUN mkdir -p /code/pjdfstest && cd /code && git clone https://github.com/fleetfs/pjdfstest && cd pjdfstest \
  && git checkout d3beed6f5f15c204a8af3df2f518241931a42e94 && autoreconf -ifs && ./configure && make pjdfstest

ENV PATH=/root/.cargo/bin:$PATH

RUN mkdir -p /code && cd /code && git clone https://github.com/fleetfs/fuse-xfstests && cd fuse-xfstests \
  && git checkout fleetfs-xfs-v2026.03.20 && make

ADD rust-toolchain /code/fleetfs/rust-toolchain

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain=$(cat /code/fleetfs/rust-toolchain)

ADD . /code/fleetfs/

RUN cd /code/fleetfs && cargo build --release && cp target/release/fleetfs /bin/fleetfs
